export const SHOE_Dialog = 'SHOE_Dialog'
export const TOPMESSAGE = 'TOPMESSAGE'
export const DELMESSAGE = 'DELMESSAGE'
export const IDEA = 'IDEA'
export const CLASS = 'CLASS'


export const FETCH_GITHUB_USER = 'FETCH_GITHUB_USER';
export const FETCH_GITHUB_USER_SUC = 'FETCH_GITHUB_USER_SUC';
export const FETCH_LESSONINFO_SUC = 'FETCH_LESSONINFO_SUC';
export const FETCH_LESSONINFO_FAI = 'FETCH_LESSONINFO_FAI';
export const FETCH_GITHUB_USER_REQ = 'FETCH_GITHUB_USER_REQ';
export const FETCH_USERINFO_FAI = 'FETCH_USERINFO_FAI';
export const FETCH_LESSONINFO_REQ = 'FETCH_LESSONINFO_REQ';



export const FETCH_USER_INFO_SUC = 'FETCH_USER_INFO_SUC';
export const FETCH_USER_INFO_FAI = 'FETCH_USER_INFO_FAI';
export const FETCH_USER_INFO_REQ = 'FETCH_USER_INFO_REQ';
export const FETCH_LESSON_INFO_SUC = 'FETCH_LESSON_INFO_SUC';
export const FETCH_LESSON_INFO_FAI = 'FETCH_LESSON_INFO_FAI';
export const FETCH_LESSON_INFO_REQ = 'FETCH_LESSON_INFO_REQ';





export const FETCH_LESSON_INFO = 'FETCH_LESSON_INFO';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';













